In [3]:
# uncomment if you are running from google colab
!pip install sklearn_crfsuite
!pip install https://github.com/PyThaiNLP/pythainlp/archive/dev.zip
!pip install fastai==1.0.46
!pip install emoji
!pip install gensim
!pip install dill
!pip install pandas
!pip install sklearn
!pip install numpy
!pip install matplotlib
!pip install pythainlp
!pip install torch
# (in anaconda terminal)
# run "ipython kernel install --name "local-venv-kernel" --user"
# (in jupyter notebook)
# kernel --> change kernel

  Using cached sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
  Created wheel for python-crfsuite: filename=python_crfsuite-0.9.7-cp39-cp39-win_amd64.whl size=164378 sha256=f15846da47b5cd4439a6c6c31939924ad6fb2ea324963120f50fc06acb19cbc3
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\07\d8\b4\63d7ef5d4c619b8f1fea39c5c5b7b52dbf014628134c144d22
Successfully built python-crfsuite
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
  Using cached tinydb-4.4.0-py3-none-any.whl (21 kB)
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
  Created wheel for pythainlp: filename=pythainlp-2.3.0.dev0-py3-none-any.whl size=11006870 sha256=549fe44a3159582c0067e3a930fada4abefc902f33780855e9de49a5339bb846
  Stored in directory: C:\Users\ASUS\AppData\Local\Temp\pip-ephem-wheel-cache-00w56h38\wheels\ea\5d\45\9b94011dd6c9fb6272aac7d49d9ccb3d6a7121d833559e

  Using cached emoji-1.2.0-py3-none-any.whl (131 kB)
  Created wheel for gensim: filename=gensim-3.8.3-cp39-cp39-win_amd64.whl size=24207966 sha256=0a08d71bb7fcc29a19445c49e2f82226e48276126596c9faaf675cac802646a3
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\ca\5d\af\618594ec2f28608c1d6ee7d2b7e95a3e9b06551e3b80a491d6
Successfully built gensim
  Using cached dill-0.3.3-py2.py3-none-any.whl (81 kB)
  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=d5f4d3f9a3c0744ca34b36033a5669eeaf04b2b4afedc3edc09b7e3c379d0ee5
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\e4\7b\98\b6466d71b8d738a0c547008b9eb39bf8676d1ff6ca4b22af1c
Successfully built sklearn


In [4]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from pythainlp.tokenize import word_tokenize
from gensim.models import KeyedVectors
import numpy as np

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

import dill as pickle
import pandas as pd
from pythainlp import word_vector
from pythainlp.word_vector import sentence_vectorizer
import tensorflow as tf

import torch


ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\Users\ASUS\anaconda3\envs\word2vec\python.exe"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.


In [101]:
def add_new_word(new_word,class_label,label_dict,vector_dict):
    vector = sentence_vectorizer(new_word, use_mean=True) 
    label_dict[TN] = class_label
    vector_dict[TN] = vector

In [100]:
df = pd.read_csv('407_dataset.csv')
label_dict = {}
vector_dict = {}

In [103]:
df_dict = df.to_dict()
for i in range(len(df_dict['Name'])):
    TN = df_dict["Name"][i].split()[0] 
    class_label = df_dict["Class"][i]
    if class_label == 'ของใช้ในชีวิตประจำวัน':
        class_label = 'ชอปปิ้ง'
    add_new_word(TN,class_label,label_dict,vector_dict)


In [104]:
for key in vector_dict:
    print(key)

ชาอินเดีย
ขนมห้อง
ข้าวเป็ดกระเทียม
มาม่าผัด
ข้าวหมูทอดมายองเนส
ข้าวยำไก่แซ่บ
เบเกอรี่
โกโก้มุก
โรตี
ไวตามิลค์
เลย์
เส้นคลุก
เค้กหน้านิ่ม
หมี่เหลืองต้มยำหมูเด้ง
กะเพราถาด
หมูกระทียมกับเล้งแซ่บ
ข้าวไก่ทงคัตสึกับเฟรนซ์ฟราย
เจียวดาว
น้ำฝรั่ง
ชามะนาว
ชิกฟิงเกอร์กับแซนด์วิชคาโบนาร่ากับโบโลน่า
ไส้กรอกอีสาน
หมูจุ่ม
กล้วยทอด
แฮปปี้โกโก้
ข้าวซอยไก่พิเศษ
ข้าวแกงกะหี่ไก่ทอด
ขายทาโกะยากิ
ขายเกี๊ยวซ่า
ขายไมโลขนม
ขายขนมจีบ
ขายสเต็กอ้วนผอม
ขายหมี่เหลืองซุปดูกต้มยำ
ขายขนม
ขายสุกี้แห้ง
ไส้กรอก
volcano
ขายชิกฟิงเกอร์
ขายแฮมชีส
มิสเตอร์โดนัท
พิซซ่า
ขายมาม่า
สเต็กไก่กับสลัดไก่กรอบ
ขายเครปเย็น
น้ำเปล่า
ขาไก่
ไข่นกกระทา
ข้าวเต้าหู้ทรงเครื่อง
ข้าวไก่ทอดราดซอสพะแนง
กาโตะ
ราชาหมูทอด
แมคโดนัลด์
มอคค่า
ข้าวหมูกระเทียม
ลาเต้
นมชมพู
ข้าวไก่ทอดทงคัตสึกับน้ำ
เลย์มาม่านมถั่วเหลืองเยลลี่
เฉาก๊วย
ลูกชิ้นกับเกี๊ยวทอด
ลูกอม
หมี่เหลืองต้มยำ
สลัดไก่กรอบ
ช็อคโกแลตเบลเยี่ยม
ข้าวยำไก่สไปซี่กับไก่สไปซี่ชิ้น
ข้าวไก่ทอดมายองเนส
ข้าวซอย
โตและสด
ลูกชิ้นสังคม
หมี่เหลืองต้มยำปลา
ขนมปังกับซีเรียลกับนม
ข้าวหมูทอดมายองเนสกับพิซซ่า
เบอร์

In [105]:
TN = 'ข้าวมันไก่'
try:
    a = vector_dict[TN]
    dist_from_1 = {}
    x = torch.from_numpy(a)
    for key in vector_dict:
        y = torch.from_numpy(vector_dict[key])
        dist = F.cosine_similarity(x,y)
        dist_from_1[key] = dist
except:
    print(TN,'not exists')
    a = sentence_vectorizer(TN, use_mean=True) 
    dist_from_1 = {}
    x = torch.from_numpy(a)
    for key in vector_dict:
        y = torch.from_numpy(vector_dict[key])
        dist = F.cosine_similarity(x,y)
        dist_from_1[key] = dist
    
    

ข้าวมันไก่ not exists


In [106]:
sorted_dict = sorted((value,key) for (key,value) in dist_from_1.items())
for key in sorted_dict:
    print(key)
    print(label_dict[key[1]])

(tensor([0.], dtype=torch.float64), 'BB')
ชอปปิ้ง
(tensor([0.], dtype=torch.float64), 'Benzac')
สุขภาพ
(tensor([0.], dtype=torch.float64), 'Counterpain')
สุขภาพ
(tensor([0.], dtype=torch.float64), 'Fidget')
บันเทิง
(tensor([0.], dtype=torch.float64), 'Gummy')
อาหาร
(tensor([0.], dtype=torch.float64), 'Internet')
บันเทิง
(tensor([0.], dtype=torch.float64), 'Netflix')
บันเทิง
(tensor([0.], dtype=torch.float64), 'arl')
การเดินทาง
(tensor([0.], dtype=torch.float64), 'carefree')
ชอปปิ้ง
(tensor([0.], dtype=torch.float64), 'cleanser')
ชอปปิ้ง
(tensor([0.], dtype=torch.float64), 'contour')
ชอปปิ้ง
(tensor([0.], dtype=torch.float64), 'jacket')
ชอปปิ้ง
(tensor([0.], dtype=torch.float64), 'mongni')
อาหาร
(tensor([0.], dtype=torch.float64), 'กะละมัง')
ของใช้ในครัวเรือน
(tensor([0.], dtype=torch.float64), 'กาต้มน้ำ')
ของใช้ในครัวเรือน
(tensor([0.], dtype=torch.float64), 'ครีมกันแดด')
ชอปปิ้ง
(tensor([0.], dtype=torch.float64), 'ครีมนวดผม')
ชอปปิ้ง
(tensor([0.], dtype=torch.float64), 'คลิปหนีบกระดา

(tensor([0.5248], dtype=torch.float64), 'โกโก้มุก')
อาหาร
(tensor([0.5327], dtype=torch.float64), 'ข้าวไก่ทอดราดซอสพะแนง')
อาหาร
(tensor([0.5337], dtype=torch.float64), 'มีดโกนหนวด')
ชอปปิ้ง
(tensor([0.5659], dtype=torch.float64), 'ข้าวแกงกะหรี่หมูทอด')
อาหาร
(tensor([0.6144], dtype=torch.float64), 'ผ่อนคอนโด')
ที่อยู่อาศัย
(tensor([0.6153], dtype=torch.float64), 'เสื้อยืด')
ชอปปิ้ง
(tensor([0.6158], dtype=torch.float64), 'ตู้เย็น')
ของใช้ในครัวเรือน
(tensor([0.6224], dtype=torch.float64), 'ผ้าห่ม')
ของใช้ในครัวเรือน
(tensor([0.6323], dtype=torch.float64), 'สำลี')
ชอปปิ้ง
(tensor([0.6363], dtype=torch.float64), 'แมคโดนัลด์')
อาหาร
(tensor([0.6393], dtype=torch.float64), 'ข้าวไก่ทอดมายองเนส')
อาหาร
(tensor([0.6416], dtype=torch.float64), 'ชาเขียวมุก')
อาหาร
(tensor([0.6439], dtype=torch.float64), 'ถุงเท้า')
ชอปปิ้ง
(tensor([0.6472], dtype=torch.float64), 'แฮปปี้โกโก้')
อาหาร
(tensor([0.6483], dtype=torch.float64), 'ช็อคโกแลตเบลเยี่ยม')
อาหาร
(tensor([0.7074], dtype=torch.float64), 'หูฟั

In [ ]:
label_dict['ข้าว'] = food